### ISSUE TITLE
filemtime(): stat failed

### ISSUE THREAD

**Issue by Venutius** [CODESIGN2/gutenberg-shortcode-preview-block#5]
I'm getting this error using WordPress 4.9.6 RC1 on a localhost install:

`filemtime():  stat failed for  C:\Users\webma\Downloads\Websites\WordPress\wordpress-4.9.6-RC1\wordpress\wp-content\plugins\gutenberg-shortcode-preview-block-master/block.build.js | 1 | wp-content/plugins/gutenberg-shortcode-preview-block-master/index.php:30`

**Comment by Venutius** [comment]
Ah sorry, just noriced I need to build this before using it.

**Comment by Lewiscowles1986** [comment]
There is a [pre-built edition in releases](https://github.com/CODESIGN2/gutenberg-shortcode-preview-block/releases). Also please see this StackOverflow https://stackoverflow.com/questions/13386082/filemtime-warning-stat-failed-for#answer-13386360
